config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  resources :progresses

  resources :workshops

  resources :workshop_scores

  resources :personalities

  resources :collages

  resources :collage_images

  resources :goal_to_dos

  resources :goal_to_bes

  resources :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/audio.rb
class Audio < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/booklet.rb
class Booklet < ActiveRecord::Base
end

app/models/collage.rb
class Collage < ActiveRecord::Base
end

app/models/color.rb
class Color < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/models/dvd.rb
class Dvd < ActiveRecord::Base
end

app/models/goal_to_be.rb
class GoalToBe < ActiveRecord::Base
end

app/models/goal_to_do.rb
class GoalToDo < ActiveRecord::Base
end

app/models/office.rb
class Office < ActiveRecord::Base
end

app/models/personality.rb
class Personality < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/progress.rb
class Progress < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/seminar.rb
class Seminar < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show, :edit, :update, :destroy]

  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render :new }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:title, :speaker, :lenght, :source)
    end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<%= form_for(@workshop) do |f| %>
  <% if @workshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
      <% @workshop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :speaker %><br>
    <%= f.text_field :speaker %>
  </div>
  <div class="field">
    <%= f.label :lenght %><br>
    <%= f.time_select :lenght %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workshops/edit.html.erb
<h1>Editing workshop</h1>

<%= render 'form' %>

<%= link_to 'Show', @workshop %> |
<%= link_to 'Back', workshops_path %>

app/views/workshops/index.html.erb
<h1>Listing workshops</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Speaker</th>
      <th>Lenght</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workshops.each do |workshop| %>
      <tr>
        <td><%= workshop.title %></td>
        <td><%= workshop.speaker %></td>
        <td><%= workshop.lenght %></td>
        <td><%= workshop.source %></td>
        <td><%= link_to 'Show', workshop %></td>
        <td><%= link_to 'Edit', edit_workshop_path(workshop) %></td>
        <td><%= link_to 'Destroy', workshop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workshop', new_workshop_path %>

app/views/workshops/new.html.erb
<h1>New workshop</h1>

<%= render 'form' %>

<%= link_to 'Back', workshops_path %>

app/views/workshops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @workshop.title %>
</p>

<p>
  <strong>Speaker:</strong>
  <%= @workshop.speaker %>
</p>

<p>
  <strong>Lenght:</strong>
  <%= @workshop.lenght %>
</p>

<p>
  <strong>Source:</strong>
  <%= @workshop.source %>
</p>

<%= link_to 'Edit', edit_workshop_path(@workshop) %> |
<%= link_to 'Back', workshops_path %>