config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  resources :progresses

  resources :workshops

  resources :workshop_scores

  resources :personalities

  resources :collages

  resources :collage_images

  resources :goal_to_dos

  resources :goal_to_bes

  resources :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/audio.rb
class Audio < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/booklet.rb
class Booklet < ActiveRecord::Base
end

app/models/collage.rb
class Collage < ActiveRecord::Base
end

app/models/collage_image.rb
class CollageImage < ActiveRecord::Base
end

app/models/color.rb
class Color < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/models/dvd.rb
class Dvd < ActiveRecord::Base
end

app/models/goal_to_be.rb
class GoalToBe < ActiveRecord::Base
end

app/models/goal_to_do.rb
class GoalToDo < ActiveRecord::Base
end

app/models/office.rb
class Office < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/progress.rb
class Progress < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/seminar.rb
class Seminar < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
end

app/controllers/collage_images_controller.rb
class CollageImagesController < ApplicationController
  before_action :set_collage_image, only: [:show, :edit, :update, :destroy]

  # GET /collage_images
  # GET /collage_images.json
  def index
    @collage_images = CollageImage.all
  end

  # GET /collage_images/1
  # GET /collage_images/1.json
  def show
  end

  # GET /collage_images/new
  def new
    @collage_image = CollageImage.new
  end

  # GET /collage_images/1/edit
  def edit
  end

  # POST /collage_images
  # POST /collage_images.json
  def create
    @collage_image = CollageImage.new(collage_image_params)

    respond_to do |format|
      if @collage_image.save
        format.html { redirect_to @collage_image, notice: 'Collage image was successfully created.' }
        format.json { render :show, status: :created, location: @collage_image }
      else
        format.html { render :new }
        format.json { render json: @collage_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collage_images/1
  # PATCH/PUT /collage_images/1.json
  def update
    respond_to do |format|
      if @collage_image.update(collage_image_params)
        format.html { redirect_to @collage_image, notice: 'Collage image was successfully updated.' }
        format.json { render :show, status: :ok, location: @collage_image }
      else
        format.html { render :edit }
        format.json { render json: @collage_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collage_images/1
  # DELETE /collage_images/1.json
  def destroy
    @collage_image.destroy
    respond_to do |format|
      format.html { redirect_to collage_images_url, notice: 'Collage image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collage_image
      @collage_image = CollageImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collage_image_params
      params.require(:collage_image).permit(:collages_id, :source)
    end
end

app/helpers/collage_images_helper.rb
module CollageImagesHelper
end

app/views/collage_images/_form.html.erb
<%= form_for(@collage_image) do |f| %>
  <% if @collage_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collage_image.errors.count, "error") %> prohibited this collage_image from being saved:</h2>

      <ul>
      <% @collage_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :collages_id %><br>
    <%= f.number_field :collages_id %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collage_images/edit.html.erb
<h1>Editing collage_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @collage_image %> |
<%= link_to 'Back', collage_images_path %>

app/views/collage_images/index.html.erb
<h1>Listing collage_images</h1>

<table>
  <thead>
    <tr>
      <th>Collages</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collage_images.each do |collage_image| %>
      <tr>
        <td><%= collage_image.collages_id %></td>
        <td><%= collage_image.source %></td>
        <td><%= link_to 'Show', collage_image %></td>
        <td><%= link_to 'Edit', edit_collage_image_path(collage_image) %></td>
        <td><%= link_to 'Destroy', collage_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collage image', new_collage_image_path %>

app/views/collage_images/new.html.erb
<h1>New collage_image</h1>

<%= render 'form' %>

<%= link_to 'Back', collage_images_path %>

app/views/collage_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Collages:</strong>
  <%= @collage_image.collages_id %>
</p>

<p>
  <strong>Source:</strong>
  <%= @collage_image.source %>
</p>

<%= link_to 'Edit', edit_collage_image_path(@collage_image) %> |
<%= link_to 'Back', collage_images_path %>