config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  resources :progresses

  resources :workshops

  resources :workshop_scores

  resources :personalities

  resources :collages

  resources :collage_images

  resources :goal_to_dos

  resources :goal_to_bes

  resources :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/audio.rb
class Audio < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/booklet.rb
class Booklet < ActiveRecord::Base
end

app/models/collage.rb
class Collage < ActiveRecord::Base
end

app/models/color.rb
class Color < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/models/dvd.rb
class Dvd < ActiveRecord::Base
end

app/models/goal_to_be.rb
class GoalToBe < ActiveRecord::Base
end

app/models/goal_to_do.rb
class GoalToDo < ActiveRecord::Base
end

app/models/office.rb
class Office < ActiveRecord::Base
end

app/models/personality.rb
class Personality < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/progress.rb
class Progress < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/seminar.rb
class Seminar < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
end

app/controllers/goal_to_dos_controller.rb
class GoalToDosController < ApplicationController
  before_action :set_goal_to_do, only: [:show, :edit, :update, :destroy]

  # GET /goal_to_dos
  # GET /goal_to_dos.json
  def index
    @goal_to_dos = GoalToDo.all
  end

  # GET /goal_to_dos/1
  # GET /goal_to_dos/1.json
  def show
  end

  # GET /goal_to_dos/new
  def new
    @goal_to_do = GoalToDo.new
  end

  # GET /goal_to_dos/1/edit
  def edit
  end

  # POST /goal_to_dos
  # POST /goal_to_dos.json
  def create
    @goal_to_do = GoalToDo.new(goal_to_do_params)

    respond_to do |format|
      if @goal_to_do.save
        format.html { redirect_to @goal_to_do, notice: 'Goal to do was successfully created.' }
        format.json { render :show, status: :created, location: @goal_to_do }
      else
        format.html { render :new }
        format.json { render json: @goal_to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goal_to_dos/1
  # PATCH/PUT /goal_to_dos/1.json
  def update
    respond_to do |format|
      if @goal_to_do.update(goal_to_do_params)
        format.html { redirect_to @goal_to_do, notice: 'Goal to do was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal_to_do }
      else
        format.html { render :edit }
        format.json { render json: @goal_to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goal_to_dos/1
  # DELETE /goal_to_dos/1.json
  def destroy
    @goal_to_do.destroy
    respond_to do |format|
      format.html { redirect_to goal_to_dos_url, notice: 'Goal to do was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal_to_do
      @goal_to_do = GoalToDo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_to_do_params
      params.require(:goal_to_do).permit(:users_id, :dream, :goal, :date)
    end
end

app/helpers/goal_to_dos_helper.rb
module GoalToDosHelper
end

app/views/goal_to_dos/_form.html.erb
<%= form_for(@goal_to_do) do |f| %>
  <% if @goal_to_do.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal_to_do.errors.count, "error") %> prohibited this goal_to_do from being saved:</h2>

      <ul>
      <% @goal_to_do.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :users_id %><br>
    <%= f.number_field :users_id %>
  </div>
  <div class="field">
    <%= f.label :dream %><br>
    <%= f.text_area :dream %>
  </div>
  <div class="field">
    <%= f.label :goal %><br>
    <%= f.text_area :goal %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goal_to_dos/edit.html.erb
<h1>Editing goal_to_do</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal_to_do %> |
<%= link_to 'Back', goal_to_dos_path %>

app/views/goal_to_dos/index.html.erb
<h1>Listing goal_to_dos</h1>

<table>
  <thead>
    <tr>
      <th>Users</th>
      <th>Dream</th>
      <th>Goal</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goal_to_dos.each do |goal_to_do| %>
      <tr>
        <td><%= goal_to_do.users_id %></td>
        <td><%= goal_to_do.dream %></td>
        <td><%= goal_to_do.goal %></td>
        <td><%= goal_to_do.date %></td>
        <td><%= link_to 'Show', goal_to_do %></td>
        <td><%= link_to 'Edit', edit_goal_to_do_path(goal_to_do) %></td>
        <td><%= link_to 'Destroy', goal_to_do, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal to do', new_goal_to_do_path %>

app/views/goal_to_dos/new.html.erb
<h1>New goal_to_do</h1>

<%= render 'form' %>

<%= link_to 'Back', goal_to_dos_path %>

app/views/goal_to_dos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Users:</strong>
  <%= @goal_to_do.users_id %>
</p>

<p>
  <strong>Dream:</strong>
  <%= @goal_to_do.dream %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @goal_to_do.goal %>
</p>

<p>
  <strong>Date:</strong>
  <%= @goal_to_do.date %>
</p>

<%= link_to 'Edit', edit_goal_to_do_path(@goal_to_do) %> |
<%= link_to 'Back', goal_to_dos_path %>